### PR TITLE
Revert "Revert "MPI supported unique particles IDs""

### PR DESCRIPTION
**Pull request by bcaddy**
Reverts cholla-hydro/cholla#101

I think the issues that caused PR #99 to fail the first time have been resolved by PR #100. Hopefully this will pass

### CODE REVIEW

**Comment by twhite-cray** [comment]
I had comments on PR #99 that apply to this request as well.

**Comment by bcaddy** [comment]
> I had comments on PR #99 that apply to this request as well.

Good catch. To double check, is it supposed to be "lower than this rank"? I've got a PR coming up that I can add this fix to

**Comment by bvillasen** [comment]
Yes, “lower than this rank” is what it should say.

**Comment by bcaddy** [comment]
Alright, I'll fix that and add it to my PR

**Pull request merged**
